"use client";

import { Loader2, Save } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  PV_ACTION_OPTIONS,
  PV_CAUSALITY_OPTIONS,
  PV_OUTCOME_OPTIONS,
  PV_SEVERITY_OPTIONS,
  PV_SERIOUSNESS_OPTIONS,
} from "@/lib/pv";
import {
  pvActionLabel,
  pvCausalityLabel,
  pvOutcomeLabel,
  pvSeriousnessLabel,
  pvSeverityLabel,
  useLanguage,
} from "@/lib/i18n";
import type {
  ADRReport,
  PVActionTaken,
  PVCausality,
  PVDrug,
  PVOutcome,
  PVPatient,
  PVReportStatus,
  PVSeverity,
} from "@/lib/types";

const inputClass =
  "h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none transition-colors focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100";
const selectClass = `${inputClass} appearance-none bg-white`;
const textareaClass =
  "min-h-28 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm text-slate-800 outline-none transition-colors focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100";

type PVReportFormProps = {
  value: ADRReport;
  onChange: (value: ADRReport) => void;
  onSubmit: () => void | Promise<void>;
  submitLabel?: string;
  busy?: boolean;
};

function Field({
  label,
  children,
  className = "",
}: {
  label: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <label className={`flex flex-col gap-1.5 ${className}`}>
      <span className="text-xs font-semibold text-slate-600">{label}</span>
      {children}
    </label>
  );
}

function SectionCard({
  title,
  description,
  children,
}: {
  title: string;
  description: string;
  children: React.ReactNode;
}) {
  return (
    <Card className="border-slate-200/70 bg-white/90 shadow-sm">
      <CardHeader className="border-b border-slate-100 pb-4">
        <CardTitle className="font-serif text-lg text-slate-800">{title}</CardTitle>
        <CardDescription className="text-xs">{description}</CardDescription>
      </CardHeader>
      <CardContent className="grid grid-cols-1 gap-4 pt-4 sm:grid-cols-2 lg:grid-cols-3">
        {children}
      </CardContent>
    </Card>
  );
}

export function PVReportForm({
  value,
  onChange,
  onSubmit,
  submitLabel,
  busy = false,
}: PVReportFormProps) {
  const { t } = useLanguage();
  const set = <K extends keyof ADRReport>(key: K, next: ADRReport[K]) =>
    onChange({ ...value, [key]: next });

  const setPatient = (patch: Partial<PVPatient>) =>
    onChange({ ...value, patient: { ...value.patient, ...patch } });

  const setDrug = (patch: Partial<PVDrug>) =>
    onChange({ ...value, drug: { ...value.drug, ...patch } });

  const toggleSeriousness = (criterion: string, checked: boolean) => {
    const current = new Set(value.seriousness_criteria || []);
    if (checked) current.add(criterion);
    else current.delete(criterion);
    set("seriousness_criteria", Array.from(current));
  };

  return (
    <form
      className="space-y-5"
      onSubmit={(event) => {
        event.preventDefault();
        void onSubmit();
      }}
    >
      <SectionCard title={t.pvForm.caseTitle} description={t.pvForm.caseDesc}>
        <Field label={t.pvForm.productDrug}>
          <input
            className={inputClass}
            value={value.product_name}
            onChange={(event) => set("product_name", event.target.value)}
            required
          />
        </Field>
        <Field label={t.pvForm.worldwideId}>
          <input
            className={inputClass}
            value={value.worldwide_unique_id ?? ""}
            onChange={(event) => set("worldwide_unique_id", event.target.value)}
            placeholder={t.pvForm.autoGenerated}
          />
        </Field>
        <Field label={t.pvForm.firstReceived}>
          <input
            type="date"
            className={inputClass}
            value={value.first_received_date ?? ""}
            onChange={(event) => set("first_received_date", event.target.value || null)}
          />
        </Field>
        <Field label={t.pvForm.caseType}>
          <select
            className={selectClass}
            value={value.case_report_type}
            onChange={(event) =>
              set("case_report_type", event.target.value as ADRReport["case_report_type"])
            }
          >
            <option value="initial">{t.pvForm.typeInitial}</option>
            <option value="followup">{t.pvForm.typeFollowup}</option>
            <option value="nullification">{t.pvForm.typeNullification}</option>
          </select>
        </Field>
        <Field label={t.pvForm.status}>
          <select
            className={selectClass}
            value={value.status}
            onChange={(event) => set("status", event.target.value as PVReportStatus)}
          >
            <option value="draft">{t.pvForm.statusDraft}</option>
            <option value="submitted">{t.pvForm.statusSubmitted}</option>
            <option value="followup">{t.pvForm.statusFollowup}</option>
            <option value="nullified">{t.pvForm.statusNullified}</option>
          </select>
        </Field>
        <Field label={t.pvForm.organisation}>
          <input
            className={inputClass}
            value={value.organization ?? ""}
            onChange={(event) => set("organization", event.target.value)}
          />
        </Field>
      </SectionCard>

      <SectionCard title={t.pvForm.patientTitle} description={t.pvForm.patientDesc}>
        <Field label={t.pvForm.identifier}>
          <input
            className={inputClass}
            value={value.patient?.identifier ?? ""}
            onChange={(event) => setPatient({ identifier: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.initials}>
          <input
            className={inputClass}
            value={value.patient?.initials ?? ""}
            onChange={(event) => setPatient({ initials: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.age}>
          <input
            type="number"
            min={0}
            className={inputClass}
            value={value.patient?.age ?? ""}
            onChange={(event) =>
              setPatient({ age: event.target.value ? Number(event.target.value) : null })
            }
          />
        </Field>
        <Field label={t.pvForm.sex}>
          <select
            className={selectClass}
            value={value.patient?.sex ?? ""}
            onChange={(event) => setPatient({ sex: event.target.value || null })}
          >
            <option value="">{t.pvForm.sexUnknown}</option>
            <option value="male">{t.pvForm.sexMale}</option>
            <option value="female">{t.pvForm.sexFemale}</option>
          </select>
        </Field>
        <Field label={t.pvForm.ageGroup}>
          <input
            className={inputClass}
            value={value.patient?.age_group ?? ""}
            onChange={(event) => setPatient({ age_group: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.dob}>
          <input
            type="date"
            className={inputClass}
            value={value.patient?.dob ?? ""}
            onChange={(event) => setPatient({ dob: event.target.value || null })}
          />
        </Field>
      </SectionCard>

      <SectionCard title={t.pvForm.reporterTitle} description={t.pvForm.reporterDesc}>
        <Field label={t.pvForm.name}>
          <input
            className={inputClass}
            value={value.reporter_name ?? ""}
            onChange={(event) => set("reporter_name", event.target.value)}
          />
        </Field>
        <Field label={t.pvForm.organisation}>
          <input
            className={inputClass}
            value={value.reporter_organisation ?? ""}
            onChange={(event) => set("reporter_organisation", event.target.value)}
          />
        </Field>
        <Field label={t.pvForm.email}>
          <input
            type="email"
            className={inputClass}
            value={value.reporter_email ?? ""}
            onChange={(event) => set("reporter_email", event.target.value)}
          />
        </Field>
        <Field label={t.pvForm.phone}>
          <input
            className={inputClass}
            value={value.reporter_phone ?? ""}
            onChange={(event) => set("reporter_phone", event.target.value)}
          />
        </Field>
        <Field label={t.pvForm.country}>
          <input
            className={inputClass}
            value={value.reporter_country ?? ""}
            onChange={(event) => set("reporter_country", event.target.value)}
          />
        </Field>
        <Field label={t.pvForm.qualification}>
          <input
            className={inputClass}
            value={value.reporter_qualification ?? ""}
            onChange={(event) => set("reporter_qualification", event.target.value)}
          />
        </Field>
      </SectionCard>

      <SectionCard title={t.pvForm.drugTitle} description={t.pvForm.drugDesc}>
        <Field label={t.pvForm.drugName}>
          <input
            className={inputClass}
            value={value.drug?.name ?? ""}
            onChange={(event) => setDrug({ name: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.dose}>
          <input
            className={inputClass}
            value={value.drug?.dose_text ?? ""}
            onChange={(event) => setDrug({ dose_text: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.route}>
          <input
            className={inputClass}
            value={value.drug?.route_of_administration ?? ""}
            onChange={(event) => setDrug({ route_of_administration: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.indication}>
          <input
            className={inputClass}
            value={value.drug?.indication ?? ""}
            onChange={(event) => setDrug({ indication: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.batchNumber}>
          <input
            className={inputClass}
            value={value.drug?.batch_number ?? ""}
            onChange={(event) => setDrug({ batch_number: event.target.value })}
          />
        </Field>
        <Field label={t.pvForm.actionTaken}>
          <select
            className={selectClass}
            value={value.drug?.action_taken ?? ""}
            onChange={(event) =>
              setDrug({ action_taken: (event.target.value || null) as PVActionTaken | null })
            }
          >
            <option value="">{t.pvForm.actionUnknown}</option>
            {PV_ACTION_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {pvActionLabel(t, option.value)}
              </option>
            ))}
          </select>
        </Field>
        <Field label={t.pvForm.therapyStart}>
          <input
            type="date"
            className={inputClass}
            value={value.drug?.therapy_start_date ?? ""}
            onChange={(event) => setDrug({ therapy_start_date: event.target.value || null })}
          />
        </Field>
        <Field label={t.pvForm.therapyEnd}>
          <input
            type="date"
            className={inputClass}
            value={value.drug?.therapy_end_date ?? ""}
            onChange={(event) => setDrug({ therapy_end_date: event.target.value || null })}
          />
        </Field>
      </SectionCard>

      <SectionCard title={t.pvForm.reactionTitle} description={t.pvForm.reactionDesc}>
        <Field label={t.pvForm.reactionTerm} className="sm:col-span-2">
          <input
            className={inputClass}
            value={value.reaction_meddra_term ?? ""}
            onChange={(event) => set("reaction_meddra_term", event.target.value)}
          />
        </Field>
        <Field label={t.pvForm.reactionOnset}>
          <input
            type="date"
            className={inputClass}
            value={value.reaction_start_date ?? ""}
            onChange={(event) => set("reaction_start_date", event.target.value || null)}
          />
        </Field>
        <Field label={t.pvForm.severity}>
          <select
            className={selectClass}
            value={value.severity ?? ""}
            onChange={(event) =>
              set("severity", (event.target.value || null) as PVSeverity | null)
            }
          >
            <option value="">{t.pvForm.severityNotAssessed}</option>
            {PV_SEVERITY_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {pvSeverityLabel(t, option.value)}
              </option>
            ))}
          </select>
        </Field>
        <Field label={t.pvForm.causality}>
          <select
            className={selectClass}
            value={value.causality ?? ""}
            onChange={(event) =>
              set("causality", (event.target.value || null) as PVCausality | null)
            }
          >
            <option value="">{t.pvForm.causalityNotAssessed}</option>
            {PV_CAUSALITY_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {pvCausalityLabel(t, option.value)}
              </option>
            ))}
          </select>
        </Field>
        <Field label={t.pvForm.outcome}>
          <select
            className={selectClass}
            value={value.outcome ?? ""}
            onChange={(event) =>
              set("outcome", (event.target.value || null) as PVOutcome | null)
            }
          >
            <option value="">{t.pvForm.outcomeUnknown}</option>
            {PV_OUTCOME_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {pvOutcomeLabel(t, option.value)}
              </option>
            ))}
          </select>
        </Field>
        <div className="flex items-end">
          <label className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm text-slate-700">
            <input
              type="checkbox"
              className="h-4 w-4 accent-indigo-600"
              checked={value.is_serious}
              onChange={(event) => set("is_serious", event.target.checked)}
            />
            {t.pvForm.seriousCase}
          </label>
        </div>
        <div className="sm:col-span-2 lg:col-span-3">
          <span className="mb-2 block text-xs font-semibold text-slate-600">
            {t.pvForm.seriousnessCriteria}
          </span>
          <div className="flex flex-wrap gap-2">
            {PV_SERIOUSNESS_OPTIONS.map((criterion) => (
              <label
                key={criterion}
                className="flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1.5 text-xs text-slate-700"
              >
                <input
                  type="checkbox"
                  className="h-3.5 w-3.5 accent-indigo-600"
                  checked={value.seriousness_criteria?.includes(criterion) ?? false}
                  onChange={(event) => toggleSeriousness(criterion, event.target.checked)}
                />
                {pvSeriousnessLabel(t, criterion)}
              </label>
            ))}
          </div>
        </div>
        <Field label={t.pvForm.narrative} className="sm:col-span-2 lg:col-span-3">
          <textarea
            className={textareaClass}
            value={value.reaction_description ?? ""}
            onChange={(event) => set("reaction_description", event.target.value)}
          />
        </Field>
      </SectionCard>

      <div className="flex justify-end">
        <Button type="submit" disabled={busy}>
          {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
          {submitLabel ?? t.pvForm.submitLabel}
        </Button>
      </div>
    </form>
  );
}
